import Routes from "@/routes";
import CheckTimeSession from "@/utils/check-event/CheckTimeSession";
import type {Metadata} from "next";
import dynamic from "next/dynamic";
import {Roboto} from "next/font/google";
import React from "react";
import "tailwindcss/tailwind.css";
import "../styles/_app.scss";
const ReduxProvider = dynamic(() => import("@/redux/redux-provider"), {
  ssr: false,
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "CMS Medpro",
  description: "Generated by Lê Quang Thái",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReduxProvider>
          <Routes children={children} />
          <CheckTimeSession />
        </ReduxProvider>
      </body>
    </html>
  );
}
