const QUERY_KEY = {
  GET_DATA_USER_IN_USE: "GET_DATA_USER_IN_USE",
  GET_FULL_USER: "GET_FULL_USER",
  GET_USER_BY_USERNAME: "GET_USER_BY_USERNAME",
  GET_LIST_CATEGORY: "GET_LIST_CATEGORY",
  GET_CATEGORY_BY_ID: "GET_CATEGORY_BY_ID",
  GET_LIST_MEDICAL_BOOKING_FORMS: "GET_LIST_MEDICAL_BOOKING_FORMS",
  GET_MEDICAL_BOOKING_FORMS_BY_ID: "GET_MEDICAL_BOOKING_FORMS_BY_ID",
  GET_LIST_HOSPITAL: "GET_LIST_HOSPITAL",
  GET_HOSPITAL_BY_ID: "GET_HOSPITAL_BY_ID",
  GET_LIST_SERVICE: "GET_LIST_SERVICE",
  GET_SERVICE_BY_ID: "GET_SERVICE_BY_ID",
};

export default QUERY_KEY;
